# Generated by Django 3.2.8 on 2021-10-16 11:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentData',
            fields=[
                ('record_id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(2147483647), django.core.validators.MinValueValidator(0)])),
                ('time_recorded', models.DateTimeField(default=datetime.datetime.now)),
                ('temperature', models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(100.0), django.core.validators.MinValueValidator(0.0)])),
                ('pressure', models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(2000.0), django.core.validators.MinValueValidator(0.0)])),
                ('humidity', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100.0), django.core.validators.MinValueValidator(0.0)])),
                ('gas_resistance', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100000.0), django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'db_table': 'environment_data',
            },
        ),
    ]
